### ISSUE TITLE
Remix

### ISSUE THREAD

**Issue by 6egic** [descampsk/wavevote#2]
Hey Kevin, 
How did you manage to compute this huge code within remix without getting vm gas errors?  I'm currently extending Patricks initial work on the voting network with some new stuff :-)

**Comment by descampsk** [comment]
Hey,

I could not compile it on Remix. I am trying to solve the gas problem to successfully put it on Ropsten.

I only succeeded with Ethereum Wallet and a old version of the compiler (geth 1.6.7). For new versions, he refuses to compile.

I will tell you here, if i manage to compile without vm gas error on remix.

Could I know which stuff you want to add :) ?

**Comment by 6egic** [comment]
Awesome man! 
I'm creating a protocol that deals with two type of actors.  
'Investigators' who can investigate objectives without linking them to their findings (Hidden what) until an investigation has been validated :-) 
Secondly, 'reviewers' who will be part of pseudo-random review panels and who must cast their vote regarding validation (Yes/no)  of previously mentioned, without being aware of the remaining participants part of the same review (hidden environment).

Please do :-) This is an interesting area of research, the more the merrier!

**Comment by SamuelRoberts96** [comment]
Not sure if this helps but with the new Remix version you can click an optimise setting on the compiler, which allows big Solidity programs to compile and be deployed. Not sure how that affects the code though.
