### ISSUE TITLE
Voters vote and wrong password

### ISSUE THREAD

**Issue by mnkhbmb** [descampsk/wavevote#3]
Hey I have question.
Where will store voters vote? 
How do combine multiple votes if multiple nodes are created?

And "Vote" password is wrong in virtualbox image
I can't unlock account

Thank you :)

**Comment by descampsk** [comment]
Hello,
Sorry for the last answer. I'm in vacations without computer.

For the password, "Vote" (without ") is for the ubuntu account and "password" without " is for the Ethereum account. If it doesnt work, i will check it. But i can't before 3 weeks.

For your initial question, I'm not sure to understand. The voters don't store the vote. Onlt the Blockchain stores the vote.
Can you explain what do you mean by 'multiple votes and multiple nodes" ?
Have a nice day ! And thanks for your question.

**Comment by descampsk** [comment]
I test it and everything work. If you have any other question, feel free to reopen the issue.
