### ISSUE TITLE
I can't start your project

### ISSUE THREAD

**Issue by chunhuiYan** [descampsk/wavevote#4]
hey dear friend
i can't run your project ,Can you provide a more detailed tutorial or video?I really want to start your project,
and i will very appreciate your tutorial.

**Comment by descampsk** [comment]
Hey,
Unfortunately I do not have access to my computer for the next two weeks, so I can not do a more advanced tutorial for now. However, I can answer your questions. On which points do you have difficulties?

**Comment by chunhuiYan** [comment]
I must to download a Virtual Box LUbuntu image?because I can't download your image.
Then I ran the project according to your procedure on my Ubuntu linux system and I meet some problems.I don' know what's mean about step5.
"1 - git clone <location> https://github.com/descampsk/wavevote/
2 - cd \<location\>/WaveVote_Electron
3 - npm install --unsafe-perm
4 - npm start
5 - To build an executable : electron-forge make"
If I want to run your project on my private Ethereum Blockchain,how to do  create a correct private Blockchain.
could you provide your  project design?
can  we chat on email?it's my email:chunhuiyan@aliyun.com.
I hope to receive your reply

**Comment by descampsk** [comment]
Issue resolved :).
